services:
  - type: web
    name: shu-ml-session406-apps
    runtime: static
    buildCommand: npm test
    staticPublishPath: .
    autoDeployTrigger: commit
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
      - path: /data/*
        name: Cache-Control
        value: public, max-age=3600
